repos:
  - repo: local
    hooks:
      - id: frontend-lint
        name: Run Lint with prettier in frontend with fix
        entry: bash
        language: system
        pass_filenames: false
        files: ^frontend/src/app/\(auth\)/.*\.(js|jsx|ts|tsx)$
        args:
          - -c
          - |
            cd frontend && npm run lint
