repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        files: "frontend/src/app/\\(auth\\)/.*\\.(js|jsx|ts|tsx)$|frontend/src/app/\\(portal\\)/.*\\.(js|jsx|ts|tsx)$"
        exclude: "frontend/src/app/\\(auth\\)/login-to-platform/page.tsx"
        types: [ file ]
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: "frontend/src/app/\\(auth\\)/.*\\.(js|jsx|ts|tsx|css|scss|json|md|html)$|frontend/src/app/\\(portal\\)/.*\\.(js|jsx|ts|tsx|css|scss|json|md|html)$"
        exclude: "frontend/src/app/(auth)/login-to-platform/page.tsx"
        args: [--write]
