repos:
  - repo: local
    hooks:
        - id: prettier_local
          name: prettier
          language: system
          entry: npx
          args:
              - prettier@3.5.3
              - --ignore-unknown
              - --write
          files: ^frontend/src/app/auth/.*\.(js|jsx|ts|tsx)$
        - id: eslint
          name: eslint
          entry: npx -y eslint
          pass_filenames: true
          language: system
          files: ^frontend/src/app/auth/.*\.(js|jsx|ts|tsx|css|scss|json|md|html)$
