repos:
  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint + Prettier fix in frontend/
        entry: bash -c 'cd frontend && npx eslint --fix $(echo "$@" | tr " " "\n" | grep "\..*/frontend/")'
        language: system
        pass_filenames: true
        files: ^frontend/.*\.(js|ts|jsx|tsx)$
