repos:
  - repo: local
    hooks:
        - id: prettier_local
          name: prettier
          language: system
          entry: npx
          args:
            - --prefix
            - frontend
            - prettier
            - --ignore-unknown
            - --write
          files: ^frontend/src/app/\(auth\)/.*\.(js|jsx|ts|tsx)$
        - id: eslint
          name: eslint
          entry: frontend\\node_modules\\.bin\\eslint.cmd
          pass_filenames: true
          language: system
          files: ^frontend/src/app/\(auth\)/.*\.(js|jsx|ts|tsx|css|scss|json|md|html)$

        - id: prettier_backend
          name: prettier (strapi backend)
          language: system
          entry: npx
          args:
            - --prefix
            - strapi-backend
            - prettier
            - --ignore-unknown
            - --write
          files: ^strapi-backend/(?!database/).*?\.(js|ts|html|json)$

        - id: eslint_backend
          name: eslint (strapi backend)
          language: system
          entry: strapi-backend\\node_modules\\.bin\\eslint.cmd
          pass_filenames: true
          files: ^strapi-backend/(?!database/).*?\.(js|ts)$
