repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        files: "frontend/.*\\.(js|jsx|ts|tsx)$"
        types: [ file ]
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: "frontend/.*\\.(js|jsx|ts|tsx|css|scss|json|md|html)$"
        args: [--write]
