version: '3.5'
services:
  frontend:
    environment:
       NEXT_PUBLIC_STRAPI_API_URL: "http://localhost:1337"
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - strapi
    ports:
      - "3000:3000"
  portaldb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
      POSTGRES_DB: strapi
  strapi:
    build:
      context: ./strapi-backend
    restart: unless-stopped
    environment:
      STRAPI_URL: 'http://localhost:1337'
      DATABASE_HOST: 'portaldb'
      NODE_ENV: 'production'
      DATABASE_CLIENT: 'postgres'
      APP_KEYS: "{}"
    ports:
      - "1337:1337"
    depends_on:
      - portaldb
  flashdata:
    build:
      context: ./littlefs-data-creator
    restart: unless-stopped
    ports:
      - "3001:3001"


