version: '3.5'
services:
  frontend:
    environment:
       NEXT_PUBLIC_STRAPI_API_URL: "localhost:1337/api"
    build:
      context: ./frontend
    
    restart: unless-stopped
    depends_on:
      - strapi
    ports:
      - "3000:3000"
  portaldb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: strapi
      POSTGRES_USER: strapi
      POSTGRES_DB: strapi
  strapi:
    build:
      context: ./strapi-backend
    restart: unless-stopped
    environment:
      DATABASE_HOST: 'portaldb'
      NODE_ENV: 'production'
      DATABASE_CLIENT: 'postgres'
      APP_KEYS: "{}"
    ports:
      - "1337:1337"
    depends_on:
      - portaldb


