/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import editorjs from "strapi-plugin-react-editorjs/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "users-permissions": usersPermissions,
    i18n: i18N,
    "duplicate-button": duplicateButton,
    menus: menus,
    editorjs: editorjs,
  },
});
